name: gcp

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Connect to instance and pull
        run: |
          gcloud compute ssh sia-project \
            --zone=asia-southeast1-c \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command='git config --global --add safe.directory /srv/bitbybit'
            --command='cd /srv/bitbybit && git pull'
